module.exports={
    UserController:require('./userController'),
    ProductController:require('./productController'),
    CategoryController:require('./categoryController'),
    BrandController:require('./brandController'),
    CouponController:require('./couponController'),
    OrderController:require('./orderController'),
    PaymentController:require('./paymentController')
}