module.exports={
    UserService:require('./userService'),
    ProductService:require('./productService'),
    CategoryService:require('./categoryService'),
    BrandService:require('./brandService'),
    CouponService:require('./couponService'),
    OrderService:require('./orderService'),
    PaymentService:require('./paymentService')
}